### ISSUE TITLE
Course 7 and Course 8 Please

### ISSUE THREAD

**Issue by naser2884** [ginny100/Meta-Front-End-Developer#4]
Hi ginny

Pls can u upload Course 7 & 8 , Please we I need it to pass the courses,

If you cant pls help me on: naser18noor@hotmail.com

Thanks

Nasser

**Comment by ginny100** [comment]
Sorry, I don't think I can. The reason is the same as in the previous issue [Final project of Advanced React course](https://github.com/ginny100/Meta-Front-End-Developer/issues/3)
